from __future__ import annotations
from typing import Optional, Protocol, Tuple


class Msg(Protocol): ...


class Cmd(Protocol):
    async def exec(self) -> Optional[Msg]: ...


class Model(Protocol):
    def init(self) -> Optional[Cmd]: ...
    def update(self, msg: Optional[Msg]) -> Tuple[Model, Optional[Cmd]]: ...
    def view(self): ...
